services:
  zerobyte-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: zerobyte
    restart: unless-stopped
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    environment:
      - NODE_ENV=development
    ports:
      - "4096:4096"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/zerobyte:/var/lib/zerobyte
      
      - ./app:/app/app
      - ~/.config/rclone:/root/.config/rclone
      # - /run/docker/plugins:/run/docker/plugins
      # - /var/run/docker.sock:/var/run/docker.sock

  zerobyte-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: zerobyte
    restart: unless-stopped
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    ports:
      - "4096:4096"
    environment:
      - ACCESS_KEY_ID=your-access-key-id
      - SECRET_ACCESS_KEY=your-secret-access-key
      - SMB_PASSWORD=your-smb-password
      - WEBDAV_PASSWORD=your-webdav-password
      - GCS_CREDENTIALS=your-gcs-credentials-json
      - AZURE_KEY=your-azure-key
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/zerobyte:/var/lib/zerobyte:rshared
      - ./zerobyte.config.json:/app/zerobyte.config.json:ro
      - ./mydata:/mydata:ro
      - /run/docker/plugins:/run/docker/plugins
      - /var/run/docker.sock:/var/run/docker.sock
